# Generated by Django 2.2.17 on 2020-12-01 10:01

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('longitude', models.CharField(blank=True, max_length=256, null=True, verbose_name='Longitude of the store')),
                ('latitude', models.CharField(blank=True, max_length=256, null=True, verbose_name='Latitude of the store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
