# Generated by Django 2.2.17 on 2020-12-05 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('waze', '0002_auto_20201203_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waze.Restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
